export const ADMIN_LOGIN_REQUEST = "LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILURE = "LOGIN_FAILURE";

export const ADMIN_LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const ADMIN_LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

